language: rust
cache: cargo
sudo: false
before_script:
  - |
      export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH &&
      pip install 'travis-cargo<0.2' --user &&
      cargo install cargo-local-pkgs --vers 0.3 --force
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUST_BACKTRACE=1
script: cargo test
after_success:
  - |
      travis-cargo --only stable doc &&
      travis-cargo --only stable doc-upload
