[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "An XML-RPC implementation for Rust"
documentation = "https://docs.rs/xmlrpc/"
repository = "https://github.com/jonas-schievink/xml-rpc-rs.git"
keywords = ["xml", "rpc", "remote", "ipc"]
categories = ["network-programming", "encoding"]
license = "CC0-1.0"
name = "xmlrpc"
version = "0.3.1"

[dependencies]
base64 = "0.3.0"
hyper = "0.10.2"
iso8601 = "0.1.1"
xml-rs = "0.3.4"
