[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "A rustic XML-RPC implementation"
license = "MIT/Apache-2.0"
name = "xmlrpc"
version = "0.1.0"

[dependencies]
base64 = "0.2.0"
chrono = "0.2.25"
hyper = "0.9.10"
xml-rs = "0.3.4"
