[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "An XML-RPC implementation for Rust"
license = "MIT/Apache-2.0"
name = "xmlrpc"
version = "0.1.0"

[dependencies]
base64 = "0.2.0"
hyper = "0.9.10"
iso8601 = "0.1.1"
xml-rs = "0.3.4"
