[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "An XML-RPC implementation for Rust"
documentation = "https://jonas-schievink.github.io/xml-rpc-rs/xmlrpc/index.html"
repository = "https://github.com/jonas-schievink/xml-rpc-rs.git"
keywords = ["xml", "rpc", "remote", "ipc"]
license = "CC0-1.0"
name = "xmlrpc"
version = "0.2.1"

[dependencies]
base64 = "0.2.0"
hyper = "0.9.10"
iso8601 = "0.1.1"
xml-rs = "0.3.4"
